AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Service for swag hunt

Parameters:
  MomentoApiKey:
    Type: String
    NoEcho: true
    Default: ''
  DefaultCache:
    Type: String
    Default: reinvent
  CORSOrigin:
    Type: String
    Default: '*'

Globals:
  Function:
    Runtime: nodejs18.x
    Architectures:
      - arm64
    Tracing: Active
    Timeout: 3
    MemorySize: 2048
    Handler: index.handler
    Environment:
      Variables:
        AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
        CORS_ORIGIN: !Ref CORSOrigin
  Api:
    Cors:
      AllowMethods: "'POST,GET,PUT,OPTIONS'"
      AllowHeaders: "'Content-Type'"
      AllowOrigin: "'*'"

Resources:
  SwagTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: type
          AttributeType: S
        - AttributeName: sort
          AttributeType: N
      GlobalSecondaryIndexes:
        - IndexName: types
          KeySchema:
            - AttributeName: type
              KeyType: HASH
            - AttributeName: sort
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  SwagBucket:
    Type: AWS::S3::Bucket
    Properties:
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - https://swaghunt.io
              - https://www.swaghunt.io
              - http://localhost:3000
            AllowedMethods:
              - PUT
            AllowedHeaders:
              - '*'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        IgnorePublicAcls: false
        BlockPublicPolicy: false
        RestrictPublicBuckets: false

  SwagApi:
    Type: AWS::Serverless::Api
    Properties:
      TracingEnabled: true
      StageName: v1
      MethodSettings:
        - MetricsEnabled: True
          ResourcePath: '/*'
          HttpMethod: '*'
          LoggingLevel: ERROR
          DataTraceEnabled: True
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: ./openapi.yaml

  AddSwagFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/add-swag
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
              Resource: !GetAtt SwagTable.Arn
            - Effect: Allow
              Action: events:PutEvents
              Resource: !Sub arn:${AWS::Partition}:events:${AWS::Region}:${AWS::AccountId}:event-bus/default
      Environment:
        Variables:
          TABLE_NAME: !Ref SwagTable
      Events:
        FromApi:
          Type: Api
          Properties:
            RestApiId: !Ref SwagApi
            Path: /swag
            Method: POST

  GetSwagFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/get-swag
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:Query
              Resource: !Sub ${SwagTable.Arn}/index/types
      Environment:
        Variables:
          TABLE_NAME: !Ref SwagTable
      Events:
        FromApi:
          Type: Api
          Properties:
            RestApiId: !Ref SwagApi
            Path: /swag
            Method: GET

  UpvoteSwagFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/upvote-swag
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:UpdateItem
              Resource: !GetAtt SwagTable.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref SwagTable
      Events:
        FromApi:
          Type: Api
          Properties:
            RestApiId: !Ref SwagApi
            Path: /swag/{from}/{type}/upvotes
            Method: POST

  CreateSwagEmbeddingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/create-swag-embedding
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: bedrock:InvokeModel
              Resource: '*'
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref MomentoSecret
      Environment:
        Variables:
          SECRET_ID: !Ref MomentoSecret
      Events:
        EmbeddingEvent:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - swag hunt
              detail-type:
                - Create Embedding

  SearchFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/search
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: bedrock:InvokeModel
              Resource: '*'
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref MomentoSecret
      Environment:
        Variables:
          SECRET_ID: !Ref MomentoSecret
      Events:
        FromApi:
          Type: Api
          Properties:
            RestApiId: !Ref SwagApi
            Path: /swag/search
            Method: POST

  GetUploadUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/get-upload-url
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: s3:PutObject
              Resource: !Sub arn:${AWS::Partition}:s3:::${SwagBucket}/quarantine/*
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref MomentoSecret
      Environment:
        Variables:
          SECRET_ID: !Ref MomentoSecret
          BUCKET_NAME: !Ref SwagBucket
          CACHE_NAME: !Ref DefaultCache
      Events:
        FromApi:
          Type: Api
          Properties:
            RestApiId: !Ref SwagApi
            Path: /swag/uploads
            Method: GET

  GetSwagDetailFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/get-swag-detail
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:Query
              Resource: !GetAtt SwagTable.Arn
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref MomentoSecret
      Environment:
        Variables:
          TABLE_NAME: !Ref SwagTable
          SECRET_ID: !Ref MomentoSecret
      Events:
        FromApi:
          Type: Api
          Properties:
            RestApiId: !Ref SwagApi
            Path: /swag/{from}/{type}
            Method: GET

  DownscalePhotoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/downscale-photo
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
              Resource: !Sub arn:${AWS::Partition}:s3:::${SwagBucket}/quarantine/*
      Layers:
        - !Ref SharpLayer
      Environment:
        Variables:
          BUCKET_NAME: !Ref SwagBucket

  SharpLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: sharp-layer
      Description: Sharp library for image processing
      ContentUri: layers/sharp-layer.zip
      CompatibleRuntimes:
        - nodejs14.x
        - nodejs18.x

  ProcessSwagStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: workflows/process-new-images.asl.json
      DefinitionSubstitutions:
        DetectModerationLabels: !Sub arn:${AWS::Partition}:states:::aws-sdk:rekognition:detectModerationLabels
        DetectLabels: !Sub arn:${AWS::Partition}:states:::aws-sdk:rekognition:detectLabels
        S3DeleteObject: !Sub arn:${AWS::Partition}:states:::aws-sdk:s3:deleteObject
        S3HeadObject: !Sub arn:${AWS::Partition}:states:::aws-sdk:s3:headObject
        S3CopyObject: !Sub arn:${AWS::Partition}:states:::aws-sdk:s3:copyObject
        S3PutObjectAcl: !Sub arn:${AWS::Partition}:states:::aws-sdk:s3:putObjectAcl
        DynamoDBPutItem: !Sub arn:${AWS::Partition}:states:::dynamodb:putItem
        LambdaInvoke: !Sub arn:${AWS::Partition}:states:::lambda:invoke
        EventBridgePutEvents: !Sub arn:${AWS::Partition}:states:::events:putEvents
        SwagBucket: !Ref SwagBucket
        SwagTable: !Ref SwagTable
        GetSwagTypeFunction: !GetAtt GetSwagTypeFunction.Arn
        DownscalePhotoFunction: !GetAtt DownscalePhotoFunction.Arn
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - rekognition:DetectModerationLabels
                - rekognition:DetectLabels
              Resource: "*"
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:DeleteObject
                - s3:HeadObject
              Resource: !Sub arn:${AWS::Partition}:s3:::${SwagBucket}/*
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:PutObjectAcl
                - s3:PutObjectStorageClass
              Resource: !Sub arn:${AWS::Partition}:s3:::${SwagBucket}/public/*
            - Effect: Allow
              Action: lambda:InvokeFunction
              Resource:
                - !GetAtt GetSwagTypeFunction.Arn
                - !GetAtt DownscalePhotoFunction.Arn
            - Effect: Allow
              Action: events:PutEvents
              Resource: !Sub arn:${AWS::Partition}:events:${AWS::Region}:${AWS::AccountId}:event-bus/default
            - Effect: Allow
              Action: dynamodb:PutItem
              Resource: !GetAtt SwagTable.Arn
      Events:
        S3ItemUploaded:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - aws.s3
              detail-type:
                - Object Created
              detail:
                bucket:
                  name:
                    - !Ref SwagBucket
                object:
                  key:
                    - prefix: quarantine/

  GetSwagTypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions\ask-ai-for-swag-type
      Timeout: 30
      Policies:
        - Statement:
            - Effect: Allow
              Action: bedrock:InvokeModel
              Resource: '*'

  MomentoSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      SecretString:
        Fn::Sub:
          - |-
            {
              "momento": "${MomentoApiKey}"
            }
          - MomentoApiKey: !Ref MomentoApiKey
